### ISSUE TITLE
Bumping dependency library versions

### ISSUE THREAD

**Issue by kimxogus** [j256/cloudwatch-logback-appender#19]
aws-sdk and logback version used in this library seems outdated.

I'm having this error and I suspect sdk version mismatch caused this. (I'm using 1.11.285 in my application)

```plain
Exception in thread "CloudWatchAppender" java.lang.NoSuchMethodError: com.amazonaws.http.ExecutionContext.setCredentials(Lcom/amazonaws/auth/AWSCredentials;)V
    at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:12365)
    at com.amazonaws.services.ec2.AmazonEC2Client.describeTags(AmazonEC2Client.java:7603)
    at com.j256.cloudwatchlogbackappender.CloudWatchAppender$CloudWatchWriter.lookupInstanceName(CloudWatchAppender.java:623)
    at com.j256.cloudwatchlogbackappender.CloudWatchAppender$CloudWatchWriter.createLogsClient(CloudWatchAppender.java:502)
    at com.j256.cloudwatchlogbackappender.CloudWatchAppender$CloudWatchWriter.writeEvents(CloudWatchAppender.java:407)
    at com.j256.cloudwatchlogbackappender.CloudWatchAppender$CloudWatchWriter.run(CloudWatchAppender.java:374)
    at java.lang.Thread.run(Thread.java:748)
```

Can you bump them?

**Comment by kimxogus** [comment]
This was my mistake. I missed adding `aws-java-sdk-ec2`

**Comment by j256** [comment]
np
