### ISSUE TITLE
Socket not created by this factory

### ISSUE THREAD

**Issue by logemann** [j256/cloudwatch-logback-appender#21]
Hi,

while testing the appender on my local environment, i am getting this:

```
java.lang.IllegalStateException: Socket not created by this factory
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.conn.ssl.SSLSocketFactory.isSecure(SSLSocketFactory.java:435)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:186)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:822)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
	at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:1799)
	at com.amazonaws.services.logs.AWSLogsClient.putLogEvents(AWSLogsClient.java:1515)
	at com.j256.cloudwatchlogbackappender.CloudWatchAppender$CloudWatchWriter.writeEvents(CloudWatchAppender.java:448)
	at com.j256.cloudwatchlogbackappender.CloudWatchAppender$CloudWatchWriter.run(CloudWatchAppender.java:374)
	at java.lang.Thread.run(Thread.java:748)
```

My appender config file is pretty standard and 1:1 from the docs. Anybody an idea?
Thanks

**Comment by logemann** [comment]
Looks like some version mismatch with the libs. I am using a quite recent httpClient library in my project and the pom of cloudwatch-logback-appender  states a quite old aws-java-sdk-logs version. Like 3 years old. Is there a reason for that?

**Comment by j256** [comment]
I've just not updated it in a while.  You are saying that the appender is not working with newer aws client jars?

**Comment by j256** [comment]
I've upgraded the AWS client jars and have not seen a problem.  Let me know if you have more information.
