### ISSUE TITLE
Submitting batch fails when contains events larger than 256 kB

### ISSUE THREAD

**Issue by fs-aikito** [j256/cloudwatch-logback-appender#23]
When a batch of log events contains one (or more) events that are larger than AWS set limit of 256 kB, submitting the whole batch fails and the events will be appended to emergency appender. I'm not actually sure what would be preferable behavior here; I feel like it would make sense to filter such events preemptively and maybe write only those particular events to emergency appender (and emit appropriate warning), allowing the rest of the events to be processed successfully.

Admittedly having log events be over 256k is bit stupid on my part, but such things do happen occasionally.

**Comment by alexvanacker** [comment]
I have the same issue (though we do need to clean our logs)

Stack trace:

```
com.amazonaws.services.logs.model.InvalidParameterException: Log event too large: 713074 bytes exceeds limit of 262144 (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: 80f4a6ac-8793-11e9-aee1-87c0ab641115)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.logs.AWSLogsClient.doInvoke(AWSLogsClient.java:2414)
        at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:2390)
        at com.amazonaws.services.logs.AWSLogsClient.executePutLogEvents(AWSLogsClient.java:1925)
        at com.amazonaws.services.logs.AWSLogsClient.putLogEvents(AWSLogsClient.java:1901)
        at com.j256.cloudwatchlogbackappender.CloudWatchAppender$CloudWatchWriter.writeEvents(CloudWatchAppender.java:448)
        at com.j256.cloudwatchlogbackappender.CloudWatchAppender$CloudWatchWriter.run(CloudWatchAppender.java:374)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by j256** [comment]
If the batch fails, maybe it should try them one by one and only emit the ones that are too large to the emergency appender?
